Create aayush.json
is-a-good-dev/register pull request #200
Opened 2022-09-27 16:31 UTC by OpAayush

2022-09-28 03:39 UTC, WilliamDavidHarrison requested changes
Please match the format: https://docs.is-a-good.dev/format

2022-09-28 14:48 UTC, OpAayush commented
Now is it correct?

2022-09-28 23:50 UTC, WilliamDavidHarrison approved these changes

2022-09-29 06:16 UTC, Tweak4141 commented
> Now is it correct? Btw are text records supported?

As I said earlier, your txt records should be with your main domain file. This file.
You also have invalid json in your file, hence the check could not pass.

2022-09-29 06:32 UTC, OpAayush commented
please can you give the code

2022-09-29 07:01 UTC, WilliamDavidHarrison commented
> please can you give the code

Check the docs.

2022-09-29 07:09 UTC, wclarkey commented
> > please can you give the code
> 
> Check the docs.

https://docs.is-a-good.dev

2022-09-29 14:24 UTC, OpAayush commented
now is it ok?

2022-09-29 20:02 UTC, wclarkey commented
Your format is still incorrect. Read this section of the docs https://docs.is-a-good.dev/format#json-example

2022-09-30 01:10 UTC, WilliamDavidHarrison requested changes

2022-09-30 01:10 UTC, WilliamDavidHarrison commented on sub-logs/aayush.json
> +  "repo": "opayush.pages.dev",
Not a valid repo, please remove this field.

2022-09-30 01:10 UTC, WilliamDavidHarrison commented on sub-logs/aayush.json
> +    "record-type": {
Change record-type to CNAME.

2022-09-30 04:50 UTC, closed without merging