Create anuj.json
is-a-good-dev/register pull request #216
Opened 2022-10-11 11:58 UTC by qanuj

2022-10-12 00:45 UTC, WilliamDavidHarrison requested changes

2022-10-12 00:45 UTC, WilliamDavidHarrison commented on sub-logs/anuj.json
> +    "URL": "https://anujpandey.com"
Sorry, we don't support URL records. Only A and CNAME. Please use a redirect service such as https://redirect.pizza

2022-10-14 19:13 UTC, Tweak4141 commented
@qanuj Please fix this.

2022-10-26 01:19 UTC, wclarkey commented
PR closed due to issue not resolved within 2 weeks.

2022-10-26 01:19 UTC, closed without merging