Update badisse.json
is-a-good-dev/register pull request #231
Opened 2022-10-29 14:18 UTC by Badisse

2022-10-29 18:57 UTC, Tweak4141 commented
@Badisse Please update the JSON file name as well.

2022-10-29 22:53 UTC, WilliamDavidHarrison requested changes
You need to change the file name to the `name` of the CNAME (please note: not the valie the name of it).

2022-10-30 01:20 UTC, wclarkey approved these changes

2022-10-30 01:22 UTC, wclarkey approved these changes

2022-10-30 01:26 UTC, merged