Create mahmud.json
is-a-good-dev/register pull request #253
Opened 2022-11-14 13:43 UTC by JBAxB8h7

2022-11-14 16:40 UTC, Tweak4141 commented
JSON file needs to match subdomain name.

2022-11-14 21:36 UTC, WilliamDavidHarrison requested changes

2022-11-14 21:36 UTC, WilliamDavidHarrison commented on sub-logs/mahmud.json
> +      "name": "JBAxB8h7",
This needs to match the JSON file name.

2022-11-14 21:37 UTC, WilliamDavidHarrison commented on sub-logs/mahmud.json
> +      "name": "JBAxB8h7",
```suggestion
      "name": "mahmud", 
```

2022-11-15 05:23 UTC, JBAxB8h7 reviewed
updated cname

2022-11-15 05:43 UTC, WilliamDavidHarrison approved these changes

2022-11-15 15:14 UTC, Tweak4141 approved these changes

2022-11-15 15:14 UTC, merged