sahil.json
is-a-good-dev/register pull request #315
Opened 2023-01-07 14:30 UTC by Sahilkhanbossking

{

  "owner": {
    "username": "Sahil@1992",
    "email": "s4h1l.ml"
  },

  "target": {
    "CNAME": {
       "name": "S4h1l.cf, 
       "value": ""
     }
    "txt": {
    "value": "replit-verify=40ad71ed-509d-4dd9-9c0c-dfb5e0725222"
  },

  "proxied": false
}

2023-01-07 15:37 UTC, KaminoCodes commented
Multiple things:
> A valid email address is required
> No cname value is supplied

2023-01-07 22:55 UTC, WilliamDavidHarrison requested changes

2023-01-07 22:55 UTC, WilliamDavidHarrison commented on sub-logs/sahil.json
> +    "email": ""
Please specify an email

2023-01-07 22:55 UTC, WilliamDavidHarrison commented on sub-logs/sahil.json
> +       "name": "",
Please add the  name of the TXT record.

2023-01-08 18:48 UTC, DIBSTERYT commented
@Sahilkhanbossking Reminder if you want this merged, we ask you fill out/fix said issues with your pull request. 👍

2023-01-13 15:09 UTC, wclarkey commented
If this is not solved in 24-48 hours, this pull request will be closed.

2023-01-15 19:19 UTC, DIBSTERYT commented
As per comment above, this pull request is now closed.

2023-01-15 19:19 UTC, closed without merging