Register my json
is-a-good-dev/register pull request #348
Opened 2023-02-02 09:37 UTC by mihir-patel-agc

2023-02-03 12:06 UTC, DIBSTERYT approved these changes

2023-02-04 16:58 UTC, DEV-DIBSTER requested changes
You need a valid CNAME record. Hit with a 404.

2023-02-06 11:36 UTC, DEV-DIBSTER commented on sub-logs/mihir-patel-agc.json
> +      "value": "https://mihir-patel-agc.is-a.dev/mihir-patel-agc-dev.github.io/"
Invalid CNAME. Please see link below:

https://support.dnsimple.com/articles/cname-record/#whats-a-cname-record

2023-02-06 11:36 UTC, DEV-DIBSTER requested changes
Invalid CNAME records. Please see link below:

https://support.dnsimple.com/articles/cname-record/#whats-a-cname-record

2023-02-07 02:56 UTC, DEV-DIBSTER approved these changes

2023-02-08 06:21 UTC, merged