Add my domain
is-a-good-dev/register pull request #349
Opened 2023-02-02 09:43 UTC by priti-shide

2023-02-03 15:36 UTC, DIBSTERYT approved these changes

2023-02-04 16:59 UTC, DEV-DIBSTER requested changes
You need a valid CNAME record. Hit with a 404.

2023-02-04 16:59 UTC, DEV-DIBSTER commented on sub-logs/priti-shide.json
> +      "value": "priti-shide-dev.github.io"
You need a valid CNAME record. Hit with a 404.

2023-02-06 21:03 UTC, DEV-DIBSTER requested changes

2023-02-06 21:03 UTC, DEV-DIBSTER commented on sub-logs/priti-shide.json
> +      "value": "https://priti-shide.is-a.dev/priti-shide-dev.github.io/"
Invalid CNAME records. Please see link below:

https://support.dnsimple.com/articles/cname-record/#whats-a-cname-record

2023-02-07 21:28 UTC, DEV-DIBSTER approved these changes

2023-02-08 06:21 UTC, merged