meet domain
is-a-good-dev/register pull request #350
Opened 2023-02-02 09:49 UTC by dudani-meet

2023-02-04 01:20 UTC, DIBSTERYT approved these changes

2023-02-04 17:00 UTC, DEV-DIBSTER commented on sub-logs/dudani-meet.json
> +      "value": "dudani-meet-dev.github.io"
priti-shide-dev.github.io

2023-02-04 17:00 UTC, DEV-DIBSTER requested changes

2023-02-04 17:00 UTC, DEV-DIBSTER commented on sub-logs/dudani-meet.json
> +      "value": "dudani-meet-dev.github.io"
You need a valid CNAME record. Hit with a 404.

2023-02-06 21:03 UTC, DEV-DIBSTER requested changes

2023-02-06 21:03 UTC, DEV-DIBSTER commented on sub-logs/dudani-meet.json
> +      "value": "https://dudani-meet.is-a.dev/dudani-meet-dev.github.io/"
Invalid CNAME records. Please see link below:

https://support.dnsimple.com/articles/cname-record/#whats-a-cname-record

2023-02-07 21:59 UTC, DEV-DIBSTER approved these changes

2023-02-08 06:21 UTC, merged