Create my domain
is-a-good-dev/register pull request #371
Opened 2023-02-02 13:30 UTC by nayan-gorasiya

2023-02-03 05:22 UTC, Tweak4141 commented
@nayan-gorasiya I am one of the maintainers here. Please let your company know that I have sent an email to them. Additionally, please tell them to reply back to me at tweak@is-a-good.dev

2023-02-04 17:07 UTC, DEV-DIBSTER requested changes

2023-02-04 17:07 UTC, DEV-DIBSTER commented on sub-logs/nayan-gorasiya.json
> +      "value": "nayan-gorasiya-dev.github.io"
You need a valid CNAME record. Hit with a 404.

2023-02-06 21:06 UTC, DEV-DIBSTER requested changes

2023-02-06 21:06 UTC, DEV-DIBSTER commented on sub-logs/nayan-gorasiya.json
> +      "value": "https://nayan-gorasiya.is-a.dev/nayan-gorasiya-dev.github.io/"
Invalid CNAME records. Please see link below:

https://support.dnsimple.com/articles/cname-record/#whats-a-cname-record

2023-02-07 21:57 UTC, DEV-DIBSTER approved these changes

2023-02-08 06:11 UTC, merged