Add my json
is-a-good-dev/register pull request #372
Opened 2023-02-02 13:34 UTC by pathan-imran

2023-02-03 05:22 UTC, Tweak4141 commented
@pathan-imran I am one of the maintainers here. Please let your company know that I have sent an email to them. Additionally, please tell them to reply back to me at tweak@is-a-good.dev

2023-02-04 17:07 UTC, DEV-DIBSTER requested changes

2023-02-04 17:07 UTC, DEV-DIBSTER commented on sub-logs/pathan-imran.json
> +      "value": "pathan-imran-dev.github.io"
You need a valid CNAME record. Hit with a 404.

2023-02-06 21:06 UTC, DEV-DIBSTER requested changes

2023-02-06 21:06 UTC, DEV-DIBSTER commented on sub-logs/pathan-imran.json
> +      "value": "https://pathan-imran.is-a.dev/pathan-imran-dev.github.io/"
Invalid CNAME records. Please see link below:

https://support.dnsimple.com/articles/cname-record/#whats-a-cname-record

2023-02-07 21:57 UTC, DEV-DIBSTER approved these changes

2023-02-08 06:10 UTC, merged