Create nitesh-rathod json file
is-a-good-dev/register pull request #374
Opened 2023-02-02 13:44 UTC by nitesh-rathod

2023-02-03 05:21 UTC, Tweak4141 commented
@nitesh-rathod I am one of the maintainers here. Please let your company know that I have sent an email to them. Additionally, please tell them to reply back to me at tweak@is-a-good.dev

2023-02-04 17:08 UTC, DEV-DIBSTER requested changes

2023-02-04 17:08 UTC, DEV-DIBSTER commented on sub-logs/nitesh-rathod.json
> +      "value": "nitesh-rathod-dev.github.io"
You need a valid CNAME record. Hit with a 404.

2023-02-06 21:07 UTC, DEV-DIBSTER requested changes

2023-02-06 21:07 UTC, DEV-DIBSTER commented on sub-logs/nitesh-rathod.json
> +      "value": "https://nitesh-rathod.is-a.dev/nitesh-rathod-dev.github.io/"
Invalid CNAME records. Please see link below:

https://support.dnsimple.com/articles/cname-record/#whats-a-cname-record

2023-02-07 21:55 UTC, DEV-DIBSTER approved these changes

2023-02-07 21:55 UTC, DEV-DIBSTER approved these changes

2023-02-08 06:09 UTC, Tweak4141 approved these changes

2023-02-08 06:09 UTC, merged