Add json file
is-a-good-dev/register pull request #375
Opened 2023-02-02 13:51 UTC by akta-chavda

2023-02-03 05:20 UTC, Tweak4141 commented
@akta-chavda Please let your company know that I have sent an email to them. Additionally, please tell them to reply back to me at tweak@is-a-good.dev

2023-02-04 17:08 UTC, DEV-DIBSTER requested changes

2023-02-04 17:08 UTC, DEV-DIBSTER commented on sub-logs/akta-chavda.json
> +      "value": "akta-chavda-dev.github.io"
You need a valid CNAME record. Hit with a 404.

2023-02-06 21:07 UTC, DEV-DIBSTER requested changes

2023-02-06 21:07 UTC, DEV-DIBSTER commented on sub-logs/akta-chavda.json
> +      "value": "https://akta-chavda.is-a.dev/akta-chavda-dev.github.io/"
Invalid CNAME records. Please see link below:

https://support.dnsimple.com/articles/cname-record/#whats-a-cname-record

2023-02-07 02:54 UTC, DEV-DIBSTER approved these changes

2023-02-08 06:07 UTC, Tweak4141 approved these changes

2023-02-08 06:08 UTC, merged