Register my domain
is-a-good-dev/register pull request #376
Opened 2023-02-02 13:56 UTC by shoaib-shaikhh

2023-02-03 05:21 UTC, Tweak4141 commented
@shoaib-shaikhh I am one of the maintainers here. Please let your company know that I have sent an email to them. Additionally, please tell them to reply back to me at tweak@is-a-good.dev

2023-02-04 17:08 UTC, DEV-DIBSTER requested changes

2023-02-04 17:08 UTC, DEV-DIBSTER commented on sub-logs/shoaib-shaikhh.json
> +      "value": "shoaib-shaikhh-dev.github.io"
You need a valid CNAME record. Hit with a 404.

2023-02-06 21:07 UTC, DEV-DIBSTER requested changes

2023-02-06 21:07 UTC, DEV-DIBSTER commented on sub-logs/shoaib-shaikhh.json
> +      "value": "https://shoaib-shaikhh.is-a.dev/shoaib-shaikhh-dev.github.io/"
Invalid CNAME records. Please see link below:

https://support.dnsimple.com/articles/cname-record/#whats-a-cname-record

2023-02-07 02:55 UTC, DEV-DIBSTER approved these changes

2023-02-07 20:34 UTC, wclarkey commented
Before this is merged, we require you to star the repository

2023-02-08 06:04 UTC, Tweak4141 approved these changes

2023-02-08 06:06 UTC, merged