add my json
is-a-good-dev/register pull request #377
Opened 2023-02-02 14:02 UTC by sharad-rajyaguru

2023-02-02 22:38 UTC, Tweak4141 commented
@sharad-rajyaguru Please let your company know that I have sent an email to them. Additionally, please tell them to reply back to me at tweak@is-a-good.dev

2023-02-04 17:09 UTC, DEV-DIBSTER requested changes

2023-02-04 17:09 UTC, DEV-DIBSTER commented on sub-logs/sharad-rajyaguru.json
> +      "value": "sharad-rajyaguru-dev.github.io"
You need a valid CNAME record. Hit with a 404.

2023-02-06 21:07 UTC, DEV-DIBSTER approved these changes

2023-02-06 21:12 UTC, Tweak4141 commented
@sharad-rajyaguru Please star the repository.

2023-02-07 20:32 UTC, wclarkey commented
@sharad-rajyaguru If the repository is not starred in 1-3 business days (GMT) this and the other pull requests will be closed.

2023-02-08 05:39 UTC, sharad-rajyaguru commented
> ```json
> sharad-rajyaguru.github.io
> ```

@Tweak4141 starred this repository

2023-02-08 06:02 UTC, Tweak4141 approved these changes

2023-02-08 06:02 UTC, merged