Create scronite.json
is-a-good-dev/register pull request #407
Opened 2023-02-24 13:52 UTC by Scronite

2023-02-24 15:54 UTC, DEV-DIBSTER requested changes

2023-02-24 15:54 UTC, DEV-DIBSTER commented on sub-logs/scronite.json
> +       "value": ""
This needs to be filled as a CNAME needs to point somewhere.

2023-02-25 16:06 UTC, DEV-DIBSTER approved these changes

2023-02-25 16:07 UTC, DEV-DIBSTER requested changes

2023-02-25 16:07 UTC, DEV-DIBSTER commented on sub-logs/scronite.json
> +       "value": "chile.zaicadiahost.xyz:5219"
Wait, this record is actually invalid.

2023-02-25 19:42 UTC, wclarkey commented
@Scronite Please make sure that your `CNAME` value is valid so that we can merge this.

2023-02-25 23:45 UTC, WilliamDavidHarrison approved these changes

2023-02-25 23:58 UTC, DEV-DIBSTER approved these changes

2023-02-26 00:00 UTC, merged