added file json
is-a-good-dev/register pull request #472
Opened 2023-04-25 09:54 UTC by jani-abhishek

2023-04-26 02:02 UTC, DEV-DIBSTER requested changes

2023-04-26 02:02 UTC, DEV-DIBSTER commented on sub-logs/jani-abhishek.json
> +      "value": "abhishek.jani@truestaz.com"
Invalid CNAME value.

2023-05-08 06:29 UTC, jani-abhishek commented on sub-logs/jani-abhishek.json
> +      "value": "abhishek.jani@truestaz.com"
This is fixed

2023-05-09 01:08 UTC, DEV-DIBSTER approved these changes

2023-06-03 01:59 UTC, closed without merging