added json file for domain
is-a-good-dev/register pull request #473
Opened 2023-04-25 09:56 UTC by mausami-parmar

2023-04-26 02:02 UTC, DEV-DIBSTER requested changes

2023-04-26 02:02 UTC, DEV-DIBSTER commented on sub-logs/mausami-parmar.json
> +      "value": "mausami.parmar@truestaz.com"
Invalid CNAME value.

2023-05-08 06:28 UTC, mausami-parmar commented on sub-logs/mausami-parmar.json
> +      "value": "mausami.parmar@truestaz.com"
This is fixed

2023-05-14 02:17 UTC, DEV-DIBSTER approved these changes

2023-05-14 03:09 UTC, WilliamDavidHarrison approved these changes

2023-05-14 03:09 UTC, merged