added file json
is-a-good-dev/register pull request #474
Opened 2023-04-25 10:03 UTC by jagruti-metaliya

2023-04-26 02:02 UTC, DEV-DIBSTER requested changes

2023-04-26 02:02 UTC, DEV-DIBSTER commented on sub-logs/jagruti-metaliya.json
> +      "value": "jagruti.metaliya@truestaz.com"
Invalid CNAME value.

2023-05-08 06:27 UTC, jagruti-metaliya commented on sub-logs/jagruti-metaliya.json
> +      "value": "jagruti.metaliya@truestaz.com"
This is fixed

2023-05-14 02:17 UTC, DEV-DIBSTER approved these changes

2023-05-14 03:09 UTC, WilliamDavidHarrison approved these changes

2023-05-14 03:09 UTC, merged