added json file for domain
is-a-good-dev/register pull request #476
Opened 2023-04-25 10:10 UTC by Bhavesh-p-Patel

2023-04-26 02:02 UTC, DEV-DIBSTER requested changes

2023-04-26 02:02 UTC, DEV-DIBSTER commented on sub-logs/Bhavesh-p-Patel.json
> +      "value": "bhavesh.patel@truestaz.com"
Invalid CNAME value.

2023-05-08 06:24 UTC, Bhavesh-p-Patel commented on sub-logs/Bhavesh-p-Patel.json
> +      "value": "bhavesh.patel@truestaz.com"
This is fixed

2023-05-13 23:28 UTC, DEV-DIBSTER requested changes

2023-05-13 23:28 UTC, DEV-DIBSTER commented on sub-logs/Bhavesh-p-Patel.json
> +      "value": "bhavesh-patel.github.io"
404 CNAME record.

2023-06-03 01:59 UTC, closed without merging