added json file for domain
is-a-good-dev/register pull request #479
Opened 2023-04-25 10:27 UTC by shakera-vora

2023-04-26 02:01 UTC, DEV-DIBSTER requested changes

2023-04-26 02:01 UTC, DEV-DIBSTER commented on sub-logs/shakera-vora.json
> +      "value": "shakera.vora@truestaz.com"
Invalid CNAME value.

2023-05-08 06:17 UTC, shakera-vora commented on sub-logs/shakera-vora.json
> +      "value": "shakera.vora@truestaz.com"
This is fixed

2023-06-01 15:25 UTC, DEV-DIBSTER approved these changes

2023-06-03 01:59 UTC, closed without merging