added json file
is-a-good-dev/register pull request #484
Opened 2023-04-25 10:45 UTC by s-kunjan

2023-04-26 02:00 UTC, DEV-DIBSTER requested changes

2023-04-26 02:00 UTC, DEV-DIBSTER commented on sub-logs/s-kunjan.json
> +      "value": "kunjan.shah@truestaz.com"
Invalid CNAME value.

2023-05-09 01:07 UTC, DEV-DIBSTER approved these changes

2023-05-16 14:32 UTC, DEV-DIBSTER commented
@Tweak4141 Are we merging any of these requests or nah?

2023-05-16 23:17 UTC, WilliamDavidHarrison approved these changes

2023-06-03 01:59 UTC, closed without merging