added json file for domain
is-a-good-dev/register pull request #488
Opened 2023-04-25 10:56 UTC by dirgha-ukani

2023-04-26 01:59 UTC, DEV-DIBSTER requested changes

2023-04-26 01:59 UTC, DEV-DIBSTER commented on sub-logs/dirgha-ukani.json
> +      "value": "dirgha.ukani@truestaz.com"
Invalid CNAME value.

2023-05-08 06:01 UTC, panchal-jatin commented on sub-logs/dirgha-ukani.json
> +      "value": "dirgha.ukani@truestaz.com"
This is fixed

2023-05-08 06:02 UTC, dirgha-ukani commented on sub-logs/dirgha-ukani.json
> +      "value": "dirgha.ukani@truestaz.com"
This is fixed

2023-05-13 23:25 UTC, DEV-DIBSTER approved these changes

2023-05-14 02:06 UTC, Tweak4141 approved these changes

2023-05-14 02:06 UTC, merged