added json file for domain
is-a-good-dev/register pull request #493
Opened 2023-04-25 11:44 UTC by patel-monal

2023-04-26 01:59 UTC, DEV-DIBSTER requested changes

2023-04-26 01:59 UTC, DEV-DIBSTER commented on sub-logs/patel-monal.jsont
Invalid file name/format

2023-04-26 01:59 UTC, DEV-DIBSTER commented on sub-logs/patel-monal.json
> +      "value": "monal.patel@truestaz.com"
Invalid CNAME value.

2023-05-08 05:59 UTC, patel-monal commented on sub-logs/patel-monal.json
> +      "value": "monal.patel@truestaz.com"
This is fixed

2023-06-03 02:00 UTC, closed without merging