added json file for domain
is-a-good-dev/register pull request #494
Opened 2023-04-25 11:52 UTC by g-pratik

2023-04-26 01:58 UTC, DEV-DIBSTER requested changes

2023-04-26 01:58 UTC, DEV-DIBSTER commented on sub-logs/g-pratik.json
> +      "value": "monal.patel@truestaz.com"
Invalid CNAME value.

2023-05-08 05:57 UTC, g-pratik commented on sub-logs/g-pratik.json
> +      "value": "monal.patel@truestaz.com"
This is fixed

2023-05-16 01:11 UTC, Tweak4141 approved these changes

2023-05-16 01:23 UTC, DEV-DIBSTER approved these changes

2023-05-16 01:23 UTC, merged