added json file for domain
is-a-good-dev/register pull request #495
Opened 2023-04-25 11:57 UTC by mayank-rathva

added json file for domain

2023-04-26 01:58 UTC, DEV-DIBSTER requested changes

2023-04-26 01:58 UTC, DEV-DIBSTER commented on sub-logs/mayank-rathva.json
> +      "value": "mayank.rathva@truestaz.com"
Invalid CNAME record.

2023-05-08 05:55 UTC, mayank-rathva commented on sub-logs/mayank-rathva.json
> +      "value": "mayank.rathva@truestaz.com"
This is fixed

2023-05-15 23:29 UTC, WilliamDavidHarrison approved these changes

2023-05-16 01:09 UTC, merged