added json file for domain
is-a-good-dev/register pull request #496
Opened 2023-04-25 12:12 UTC by patel-komal

added json file for domain

2023-04-26 01:58 UTC, DEV-DIBSTER requested changes

2023-05-08 05:53 UTC, patel-komal commented on sub-logs/patel-komal.json
> +      "value": "komal.patel@truestaz.com"
This is fixed.

2023-05-15 16:33 UTC, Tweak4141 approved these changes

2023-05-15 20:19 UTC, DEV-DIBSTER approved these changes

2023-05-15 20:19 UTC, merged