Register headlance.dev.is-a-good.dev
is-a-good-dev/register pull request #511
Opened 2023-06-05 18:06 UTC by chargercreepy001

Added `headlance.dev.is-a-good.dev` using the [CLI](https://www.npmjs.com/package/@is-a-good-dev/cli).

2023-06-05 18:07 UTC, DEV-DIBSTER requested changes

2023-06-05 18:07 UTC, DEV-DIBSTER commented on sub-logs/headlance.dev.json
> +            "value": "300"
Value is not needed.

2023-06-05 18:08 UTC, chargercreepy001 commented on sub-logs/headlance.dev.json
> +            "value": "300"
ok

2023-06-08 16:57 UTC, DEV-DIBSTER commented
@chargercreepy001 You didn't change anything in the file. Please correct the file with proper JSON properties.

2023-06-12 16:48 UTC, closed without merging