Register htmldev.is-a-good.dev
is-a-good-dev/register pull request #536
Opened 2023-07-11 08:36 UTC by BeastYTX

Added `htmldev.is-a-good.dev` using the [CLI](https://www.npmjs.com/package/@is-a-good-dev/cli).

2023-07-11 18:20 UTC, DEV-DIBSTER requested changes

2023-07-11 18:20 UTC, DEV-DIBSTER commented on sub-logs/htmldev.json
> +            "value": "25faa1b9d2-hosting.gitbook.io"
404 value, nothing is displayed.

2023-07-13 15:05 UTC, BeastYTX commented
What??

2023-07-13 16:40 UTC, DEV-DIBSTER commented
> 25faa1b9d2-hosting.gitbook.io

![image](https://github.com/is-a-good-dev/register/assets/76603072/4616b992-3c97-4ef5-beda-c660e9ab61a1)

2023-07-14 05:13 UTC, BeastYTX commented on sub-logs/htmldev.json
> +            "value": "25faa1b9d2-hosting.gitbook.io"
????

2023-07-16 00:44 UTC, DEV-DIBSTER commented
Closed for inactivity.

2023-07-16 00:44 UTC, closed without merging