Fixed sub-domain json file
is-a-good-dev/register pull request #634
Opened 2024-03-19 07:20 UTC by aadirajuthup

Hopefully all previous issues are fixed now. I've referenced already existing entries and modified my file accordingly.

2024-03-21 03:49 UTC, DEV-DIBSTER requested changes

2024-03-21 03:49 UTC, DEV-DIBSTER commented on sub-logs/aadi.json
> +		"CNAME": {
Cannot have CNAME and TXT records.

2024-03-21 04:00 UTC, Tweak4141 commented
We also don't support vercel.

2024-03-25 00:44 UTC, clarkedev commented
@aadirajuthup I am closing this pull request. If you still need the domain, you can solve these issues and reapply.

2024-03-25 00:44 UTC, closed without merging