Register `avengers-sonarqube.is-a-good.dev`
is-a-good-dev/register pull request #638
Opened 2024-04-12 01:54 UTC by hxhieu

2024-04-12 02:28 UTC, Tweak4141 commented on sub-logs/avengers-sonarqube.json
> +        "name": "www",
Should be avengers-sonarqube

2024-04-12 02:29 UTC, Tweak4141 requested changes
Name must be subdomain value.

2024-04-12 02:29 UTC, Tweak4141 commented on sub-logs/avengers-sonarqube.json
> +        "name": "asuid.www",
asuid.avengers-sonarqube

2024-04-12 02:29 UTC, Tweak4141 commented on sub-logs/avengers-sonarqube.json
> +        "name": "www",
avengers-sonarqube

2024-04-14 20:37 UTC, hxhieu commented on sub-logs/avengers-sonarqube.json
> +        "name": "www",
Thanks and fixed

2024-04-14 21:09 UTC, Tweak4141 approved these changes

2024-04-14 21:09 UTC, merged