Register khalil.is-a-good.dev
is-a-good-dev/register pull request #677
Opened 2024-08-14 03:33 UTC by medkhalilbk

Added `khalil.is-a-good.dev` using the [CLI](https://www.npmjs.com/package/@is-a-good-dev/cli).

2024-08-14 05:18 UTC, Tweak4141 requested changes

2024-08-14 05:18 UTC, Tweak4141 commented on sub-logs/khalil.json
Invalid A record.

2024-08-15 03:51 UTC, medkhalilbk commented on sub-logs/khalil.json
Hello i got error after adding TXT record from Vercel

![image](https://github.com/user-attachments/assets/0247833e-2583-476a-bbaf-a7d9a9e30340)

2024-08-15 03:56 UTC, Tweak4141 commented on sub-logs/khalil.json
We do not support vercel

2024-08-15 03:59 UTC, medkhalilbk commented on sub-logs/khalil.json
Thank you for your prompt response 🙏

2024-08-21 16:39 UTC, closed without merging