Create global.json
is-a-good-dev/register pull request #678
Opened 2024-08-20 18:37 UTC by ImPosh

2024-08-20 19:59 UTC, DEV-DIBSTER requested changes

2024-08-20 19:59 UTC, DEV-DIBSTER commented on sub-logs/global.json
> +    "record-type": {
Record type not specified.

2024-08-21 15:34 UTC, ImPosh reviewed
fixed

2024-08-21 16:44 UTC, DEV-DIBSTER requested changes

2024-08-21 16:44 UTC, DEV-DIBSTER commented on sub-logs/global.json
> +       "value": "https://globalwidegames.github.io"
For a CNAME record, it should be a hostname with no protocols.

2024-08-21 16:57 UTC, ImPosh reviewed
fixed it again mb

2024-08-21 17:32 UTC, DEV-DIBSTER approved these changes

2024-08-21 17:33 UTC, merged